### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/'

### ISSUE THREAD

**Issue by tachikoma777** [ForeverPs/content-aware-rotation#1]
Error while calling lsd, is anything missing?

Traceback (most recent call last):
  File "main.py", line 97, in <module>
    image_rotation(img_path, angle)
  File "main.py", line 41, in image_rotation
    lines = detect_lines(img_array, angle, x_len, y_len, x, y, M=M)
  File "/home/work/buildingCorrection/content-aware-rotation-master/lsd_detect_lines.py", line 9, in detect_lines
    lines = lsd(gray)
  File "/home/work/buildingCorrection/content-aware-rotation-master/lsd/lsd.py", line 15, in lsd
    fp = open(temp, 'r')
IsADirectoryError: [Errno 21] Is a directory: '/'

**Comment by ForeverPs** [comment]
Hi，glad to receive your email.


You are right, I think you are runing this project on Linux.


Just now,&nbsp; I tried to run the project on a server, and I got the same error just like yours.


You can try it again on Windows, I believe it will work well.


You know, there are always something different between Linux and Windows on IO operation.


Besides, the lsd method which I used in the project was also from github,&nbsp;


I didn't pay much attention to its details.


All in all, this is a problem about IO operation which occurs in lsd/lsd.py


Finally, best wishes and I will handle this bug when I am free.


Again, very glad to receive your email, may you have&nbsp; a good day.










&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ForeverPs/content-aware-rotation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月28日(星期一) 下午4:09
收件人:&nbsp;"ForeverPs/content-aware-rotation"<content-aware-rotation@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[ForeverPs/content-aware-rotation] IsADirectoryError: [Errno 21] Is a directory: '/' (#1)





 
Error while calling lsd, is anything missing?
 
Traceback (most recent call last):
 File "main.py", line 97, in 
 image_rotation(img_path, angle)
 File "main.py", line 41, in image_rotation
 lines = detect_lines(img_array, angle, x_len, y_len, x, y, M=M)
 File "/home/work/buildingCorrection/content-aware-rotation-master/lsd_detect_lines.py", line 9, in detect_lines
 lines = lsd(gray)
 File "/home/work/buildingCorrection/content-aware-rotation-master/lsd/lsd.py", line 15, in lsd
 fp = open(temp, 'r')
 IsADirectoryError: [Errno 21] Is a directory: '/'

**Comment by tachikoma777** [comment]
I dont know why but this seems works for me in Linux
https://github.com/primetang/pylsd/issues/8#issuecomment-402995490
